@tool
extends RefCounted

# ─── Embedded assets ────────────────────────────────────────────────────────

const BOOST_LICENSE := """Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
"""

const AUTO_MARKER := "# --- Automated Dependencies (Managed by Script) ---"
const MANUAL_MARKER := "# --- Manually Add Dependencies Here  ---"
const ORG_REPO := "https://github.com/ChillCube/.github.git"

# ─── Low-level helpers ───────────────────────────────────────────────────────

static func _exec(cmd: String, args: Array, log: Callable) -> int:
	var psa := PackedStringArray()
	for a in args:
		psa.append(str(a))
	var output := []
	var code := OS.execute(cmd, psa, output, true)
	if log.is_valid() and not output.is_empty():
		for line: String in output[0].split("\n"):
			if not line.strip_edges().is_empty():
				log.call(line)
	return code

static func _git(args: Array, cwd: String, log: Callable) -> int:
	var full := ["-C", cwd] + args if not cwd.is_empty() else args
	return _exec("git", full, log)

static func _gh(args: Array, log: Callable) -> int:
	# gh is often installed outside Godot's PATH.
	# Try progressively broader shell contexts until one works.
	var parts: Array[String] = []
	for a in args:
		var s := str(a)
		parts.append("'" + s.replace("'", "'\"'\"'") + "'")
	var inner := "gh " + " ".join(PackedStringArray(parts))
	# Source all common rc files so PATH is fully populated
	var preamble := ". ~/.bashrc 2>/dev/null; . ~/.bash_profile 2>/dev/null; . ~/.profile 2>/dev/null; "
	var attempts: Array = [
		["bash", ["-lc", inner]],
		["bash", ["-c", preamble + inner]],
		["bash", ["-c", "export PATH=\"$PATH:/usr/local/bin:/usr/bin:/snap/bin:/home/linuxbrew/.linuxbrew/bin\"; " + inner]],
	]
	for attempt: Array in attempts:
		var output := []
		var code := OS.execute(str(attempt[0]), PackedStringArray(attempt[1] as Array[String]), output, true)
		var out_str: String = output[0] if not output.is_empty() else ""
		var not_found := out_str.contains("command not found") or out_str.contains("No such file")
		if log.is_valid() and not out_str.is_empty() and not not_found:
			for line: String in out_str.split("\n"):
				if not line.strip_edges().is_empty():
					log.call(line)
		if not not_found:
			return code
	if log.is_valid():
		log.call("❌ gh CLI not found.")
		log.call("   Install: https://cli.github.com")
		log.call("   Then run:  gh auth login")
	return FAILED

static func _read(path: String) -> String:
	if not FileAccess.file_exists(path):
		return ""
	var f := FileAccess.open(path, FileAccess.READ)
	if not f:
		return ""
	var s := f.get_as_text()
	f.close()
	return s

static func _write(path: String, content: String) -> bool:
	var f := FileAccess.open(path, FileAccess.WRITE)
	if not f:
		return false
	f.store_string(content)
	f.close()
	return true

static func _rm_rf(path: String) -> void:
	_exec("rm", ["-rf", path], Callable())

static func _mv(from: String, to: String) -> void:
	_exec("mv", [from, to], Callable())

static func _find(base: String, pattern: String) -> Array[String]:
	var result: Array[String] = []
	var dir := DirAccess.open(base)
	if not dir:
		return result
	dir.list_dir_begin()
	var name := dir.get_next()
	while name != "":
		if not name.begins_with("."):
			var full := base + "/" + name
			if dir.current_is_dir():
				result.append_array(_find(full, pattern))
			elif _match(name, pattern):
				result.append(full)
		name = dir.get_next()
	dir.list_dir_end()
	return result

static func _match(name: String, pattern: String) -> bool:
	if not pattern.contains("*"):
		return name == pattern
	var parts := pattern.split("*", false)
	if parts.size() == 2:
		return name.begins_with(parts[0]) and name.ends_with(parts[1])
	return name == pattern

# ─── Addon metadata ──────────────────────────────────────────────────────────

static func list_addons(project_root: String) -> Array[String]:
	var result: Array[String] = []
	var dir := DirAccess.open(project_root + "/addons")
	if not dir:
		return result
	dir.list_dir_begin()
	var name := dir.get_next()
	while name != "":
		if dir.current_is_dir() and not name.begins_with("."):
			if FileAccess.file_exists(project_root + "/addons/" + name + "/plugin.cfg"):
				result.append(name)
		name = dir.get_next()
	dir.list_dir_end()
	return result

static func parse_cfg(path: String) -> Dictionary:
	var out := {"name": "", "description": "", "author": "", "version": "0.1.0", "category": "Uncategorized"}
	for line: String in _read(path).split("\n"):
		for key in out.keys():
			if line.begins_with(key + "="):
				var val := line.split("=", true, 1)[1].strip_edges()
				if val.begins_with('"') and val.ends_with('"'):
					val = val.substr(1, val.length() - 2)
				out[key] = val
	return out

static func git_remote(addon_path: String) -> String:
	# Read .git/config directly — more reliable than running git in Godot's PATH
	var git_path := addon_path + "/.git"
	var config_path := ""
	if DirAccess.dir_exists_absolute(git_path):
		config_path = git_path + "/config"
	elif FileAccess.file_exists(git_path):
		# .git is a file (submodule/worktree) pointing to the real git dir
		var gf := FileAccess.open(git_path, FileAccess.READ)
		if gf:
			var line := gf.get_as_text().strip_edges()
			gf.close()
			if line.begins_with("gitdir: "):
				config_path = addon_path + "/" + line.substr(8).strip_edges() + "/config"
	if not config_path.is_empty() and FileAccess.file_exists(config_path):
		var cf := FileAccess.open(config_path, FileAccess.READ)
		if cf:
			var in_origin := false
			for line: String in cf.get_as_text().split("\n"):
				var t := line.strip_edges()
				if t == '[remote "origin"]':
					in_origin = true
				elif t.begins_with("[") and in_origin:
					break
				elif in_origin and t.begins_with("url = "):
					cf.close()
					return _normalise_remote_url(t.substr(6).strip_edges())
			cf.close()
	# Fallback: run git, take first non-error line
	var output := []
	OS.execute("git", PackedStringArray(["-C", addon_path, "remote", "get-url", "origin"]), output, false)
	if not output.is_empty():
		for line: String in (output[0] as String).split("\n"):
			var t := line.strip_edges()
			if not t.is_empty() and not t.begins_with("fatal") and not t.begins_with("error"):
				return _normalise_remote_url(t)
	return ""

static func _normalise_remote_url(url: String) -> String:
	url = url.replace(".git", "")
	url = url.replace("git@github.com:", "https://github.com/")
	url = url.replace("ssh://git@github.com/", "https://github.com/")
	return url

static func is_chillcube(url: String) -> bool:
	return url.to_lower().contains("github.com/chillcube/")

# ─── CREATE ADDON ────────────────────────────────────────────────────────────

static func create_addon(root: String, addon_name: String, desc: String, author: String, category: String, create_gh: bool, log: Callable) -> bool:
	var safe := addon_name.replace(" ", "_")
	var target := root + "/addons/" + safe
	log.call("📂 Creating: " + target)

	if DirAccess.dir_exists_absolute(target):
		log.call("❌ Folder already exists: " + target)
		return false

	if DirAccess.make_dir_recursive_absolute(target) != OK:
		log.call("❌ Could not create directory.")
		return false

	log.call("🔧 Initializing Git...")
	_git(["init", "-q"], target, log)
	_git(["branch", "-m", "main"], target, log)

	_write(target + "/.gitignore", ".godot/\n*.import/\n*.tmp\n")
	_write(target + "/DEPENDENCIES.txt", AUTO_MARKER + "\n\n" + MANUAL_MARKER + "\n")

	var cfg := "[plugin]\nname=\"%s\"\ndescription=\"%s\"\nauthor=\"%s\"\nversion=\"0.1.0\"\ncategory=\"%s\"\nscript=\"\"\n" \
		% [addon_name, desc, author, category]
	_write(target + "/plugin.cfg", cfg)

	log.call("⚖️  Writing LICENSE...")
	_write(target + "/LICENSE", BOOST_LICENSE)

	log.call("📝 Generating README...")
	var year := str(Time.get_datetime_dict_from_system()["year"])
	_write(target + "/README.md", _readme(safe, desc, author, year, ""))

	log.call("📦 Initial commit...")
	_git(["add", "."], target, log)
	_git(["commit", "-m", "initial: initialize " + addon_name + " as a ChillCube addon"], target, log)

	if create_gh:
		log.call("🌐 Creating GitHub repo: ChillCube/" + safe)
		var code := _gh(["repo", "create", "ChillCube/" + safe,
			"--public", "--source=" + target, "--remote=origin", "--push"], log)
		if code != OK:
			log.call("⚠️  GitHub repo was not created — see messages above")

	log.call("✅ Done! addons/" + safe)
	return true

# ─── SYNC ADDON ──────────────────────────────────────────────────────────────
static func has_changes(addon_path: String) -> bool:
	if not DirAccess.dir_exists_absolute(addon_path + "/.git"):
		return false
	# Uncommitted local changes
	var local_out: Array = []
	OS.execute("git", PackedStringArray(["-C", addon_path, "status", "--porcelain"]), local_out, true)
	if not local_out.is_empty() and not (local_out[0] as String).strip_edges().is_empty():
		return true
	# Local commits not yet pushed
	var ahead_out: Array = []
	OS.execute("git", PackedStringArray(["-C", addon_path, "rev-list", "--count", "origin/main..HEAD"]), ahead_out, true)
	if not ahead_out.is_empty() and (ahead_out[0] as String).strip_edges().to_int() > 0:
		return true
	# Remote commits not yet pulled (uses cached remote refs)
	var behind_out: Array = []
	OS.execute("git", PackedStringArray(["-C", addon_path, "rev-list", "--count", "HEAD..origin/main"]), behind_out, true)
	if not behind_out.is_empty() and (behind_out[0] as String).strip_edges().to_int() > 0:
		return true
	return false



static func sync_addon(root: String, url: String, log: Callable) -> bool:
	var addons_dir := root + "/addons"
	var clean_url := url.replace(".git", "").replace("git@github.com:", "https://github.com/")
	var dir := DirAccess.open(addons_dir)
	if dir:
		dir.list_dir_begin()
		var name := dir.get_next()
		while name != "":
			if dir.current_is_dir() and not name.begins_with("."):
				var apath := addons_dir + "/" + name
				var remote := git_remote(apath)
				if remote == clean_url:
					log.call("🔄 Syncing: " + name)
					# 1. Commit any local changes so they survive the rebase
					var status_out: Array = []
					OS.execute("git", PackedStringArray(["-C", apath, "status", "--porcelain"]), status_out, true)
					var dirty := not status_out.is_empty() and not (status_out[0] as String).strip_edges().is_empty()
					if dirty:
						log.call("📝 Committing local changes...")
						_git(["add", "."], apath, log)
						_git(["commit", "-m", "sync: local changes"], apath, log)
					# 2. Pull remote changes, rebasing local commits on top
					log.call("⬇️  Pulling from remote...")
					var pull_ok := _git(["pull", "--rebase", "origin", "main"], apath, log) == OK
					if not pull_ok:
						log.call("⚠️  Merge conflict — resolve manually in addons/" + name)
						_git(["rebase", "--abort"], apath, Callable())
						return false
					# 3. Push back — only for ChillCube-owned repos
					if is_chillcube(clean_url):
						log.call("⬆️  Pushing to remote...")
						var push_ok := _git(["push", "origin", "main"], apath, log) == OK
						log.call("✅ Synced!" if push_ok else "⚠️  Push failed — check your remote access.")
						return push_ok
					else:
						log.call("✅ Pulled latest. (Push skipped — not a ChillCube addon.)")
						return true
			name = dir.get_next()
		dir.list_dir_end()
	return clone_addon(root, url, log)

# ─── CLONE ADDON ─────────────────────────────────────────────────────────────

static func clone_addon(root: String, repo_url: String, log: Callable) -> bool:
	var addons_dir := root + "/addons"
	DirAccess.make_dir_recursive_absolute(addons_dir)

	var tmp := OS.get_temp_dir() + "/.cc_clone_" + str(int(Time.get_unix_time_from_system()))
	log.call("📥 Cloning: " + repo_url)

	if _git(["clone", "--quiet", repo_url, tmp], "", log) != OK:
		log.call("❌ Clone failed.")
		return false

	var installed: Array[String] = []
	var cfgs := _find(tmp, "plugin.cfg")

	if cfgs.is_empty():
		var aname := repo_url.get_file().replace(".git", "")
		var target := addons_dir + "/" + aname
		log.call("📦 Installing (no plugin.cfg): " + aname)
		_mv(tmp, target)
		installed.append(target)
	else:
		for cfg_path: String in cfgs:
			var addon_dir := cfg_path.get_base_dir()
			if addon_dir == tmp:
				var aname := repo_url.get_file().replace(".git", "")
				var target := addons_dir + "/" + aname
				log.call("📦 Installing (repo root): " + aname)
				_mv(tmp, target)
				installed.append(target)
				break
			else:
				var aname := addon_dir.get_file()
				var target := addons_dir + "/" + aname
				log.call("📦 Installing: " + aname)
				_mv(addon_dir, target)
				_git(["init", "-q"], target, log)
				_git(["remote", "add", "origin", repo_url], target, log)
				installed.append(target)
	_rm_rf(tmp)

	for addon_path: String in installed:
		for cfg: String in _find(addon_path, "plugin.cfg"):
			_enable_plugin(root, cfg.replace(root + "/", ""), log)

	_install_deps(root, installed, log)
	log.call("✅ Done!")
	return true

static func _install_deps(root: String, installed: Array[String], log: Callable) -> void:
	var addons_dir := root + "/addons"
	var class_url := _build_class_map(addons_dir)

	for addon_path: String in installed:
		var dep_file := addon_path + "/DEPENDENCIES.txt"
		if not FileAccess.file_exists(dep_file):
			_write(dep_file, AUTO_MARKER + "\n\n" + MANUAL_MARKER + "\n")

		var self_url := git_remote(addon_path)
		var existing := _read(dep_file)
		var found: Array[String] = []

		var re := RegEx.new()
		re.compile("\\b[A-Z][A-Za-z0-9_]+\\b")
		for gf: String in _find(addon_path, "*.gd"):
			for m: RegExMatch in re.search_all(_read(gf)):
				var word := m.get_string()
				if word in class_url:
					var url: String = class_url[word]
					if url != self_url and url not in existing and url not in found:
						found.append(url)
						log.call("🔍 Auto-dep: " + url.get_file())

		if not found.is_empty():
			var block := AUTO_MARKER + "\n"
			for u: String in found:
				block += u + "\n"
			existing = existing.replace(AUTO_MARKER + "\n", block)
			_write(dep_file, existing)

	# Recursive install
	for dep_file: String in _find(addons_dir, "DEPENDENCIES.txt"):
		for line: String in _read(dep_file).split("\n"):
			line = line.strip_edges()
			if line.begins_with("http"):
				var dep_name := line.rstrip("/").get_file().replace(".git", "")
				if not DirAccess.dir_exists_absolute(addons_dir + "/" + dep_name):
					log.call("🔗 Installing dependency: " + dep_name)
					clone_addon(root, line, log)

static func _build_class_map(addons_dir: String) -> Dictionary:
	var result := {}
	var dir := DirAccess.open(addons_dir)
	if not dir:
		return result
	dir.list_dir_begin()
	var name := dir.get_next()
	while name != "":
		if dir.current_is_dir() and not name.begins_with("."):
			var addon_path := addons_dir + "/" + name
			var url := git_remote(addon_path)
			if not url.is_empty():
				for gf: String in _find(addon_path, "*.gd"):
					for line: String in _read(gf).split("\n"):
						if line.begins_with("class_name "):
							var cname := line.replace("class_name ", "").strip_edges().split(" ")[0].split(":")[0]
							if not cname.is_empty():
								result[cname] = url
		name = dir.get_next()
	dir.list_dir_end()
	return result

static func _enable_plugin(root: String, cfg_rel: String, log: Callable) -> void:
	var pfile := root + "/project.godot"
	if not FileAccess.file_exists(pfile):
		return
	var res := "res://" + cfg_rel
	var content := _read(pfile)
	if res in content:
		return

	if "[editor_plugins]" in content:
		var re := RegEx.new()
		re.compile("enabled=PackedStringArray\\(([^)]*)\\)")
		var m := re.search(content)
		if m:
			var inner := m.get_string(1).strip_edges()
			var entry := '"' + res + '"'
			var new_inner := (inner + ", " + entry) if inner != "" else entry
			content = content.replace(m.get_string(), "enabled=PackedStringArray(" + new_inner + ")")
		else:
			content = content.replace("[editor_plugins]",
				'[editor_plugins]\n\nenabled=PackedStringArray("' + res + '")')
	else:
		content += '\n[editor_plugins]\n\nenabled=PackedStringArray("' + res + '")\n'

	_write(pfile, content)
	log.call("⚡ Enabled: " + cfg_rel)

static func get_dependents(root: String) -> Dictionary:
	var addons_dir := root + "/addons"
	# Build url -> folder map for all installed addons
	var url_to_folder := {}
	var dir := DirAccess.open(addons_dir)
	if dir:
		dir.list_dir_begin()
		var name := dir.get_next()
		while name != "":
			if dir.current_is_dir() and not name.begins_with("."):
				var url := git_remote(addons_dir + "/" + name)
				if not url.is_empty():
					url_to_folder[url] = name
			name = dir.get_next()
		dir.list_dir_end()
	# Walk every DEPENDENCIES.txt and record who depends on whom
	var result := {}  # dep_folder -> [depender_folder, ...]
	var dir2 := DirAccess.open(addons_dir)
	if dir2:
		dir2.list_dir_begin()
		var name2 := dir2.get_next()
		while name2 != "":
			if dir2.current_is_dir() and not name2.begins_with("."):
				for line: String in _read(addons_dir + "/" + name2 + "/DEPENDENCIES.txt").split("\n"):
					var l := line.strip_edges()
					if l.begins_with("http"):
						var clean := l.replace(".git", "").replace("git@github.com:", "https://github.com/")
						if clean in url_to_folder:
							var dep: String = url_to_folder[clean]
							if dep not in result:
								result[dep] = []
							(result[dep] as Array).append(name2)
			name2 = dir2.get_next()
		dir2.list_dir_end()
	return result

# ─── DEPENDENCY EDITING ──────────────────────────────────────────────────────

static func read_dep_urls(addon_path: String) -> Array[String]:
	var result: Array[String] = []
	for line: String in _read(addon_path + "/DEPENDENCIES.txt").split("\n"):
		line = line.strip_edges()
		if line.begins_with("http"):
			var clean := line.replace(".git", "").replace("git@github.com:", "https://github.com/")
			if clean not in result:
				result.append(clean)
	return result

static func add_dep(addon_path: String, dep_url: String) -> void:
	var dep_file := addon_path + "/DEPENDENCIES.txt"
	var content := _read(dep_file)
	if content.is_empty():
		content = AUTO_MARKER + "\n\n" + MANUAL_MARKER + "\n"
	var clean := dep_url.replace(".git", "").replace("git@github.com:", "https://github.com/")
	if clean in content or dep_url in content:
		return
	if MANUAL_MARKER in content:
		content = content.replace(MANUAL_MARKER + "\n", MANUAL_MARKER + "\n" + clean + "\n")
	else:
		content += "\n" + MANUAL_MARKER + "\n" + clean + "\n"
	_write(dep_file, content)

static func remove_dep(addon_path: String, dep_url: String) -> void:
	var dep_file := addon_path + "/DEPENDENCIES.txt"
	var content := _read(dep_file)
	if content.is_empty():
		return
	var clean := dep_url.replace(".git", "").replace("git@github.com:", "https://github.com/")
	var new_lines: Array[String] = []
	for line: String in content.split("\n"):
		var t := line.strip_edges().replace(".git", "").replace("git@github.com:", "https://github.com/")
		if t != clean:
			new_lines.append(line)
	_write(dep_file, "\n".join(PackedStringArray(new_lines)))

# ─── REMOVE ADDON ────────────────────────────────────────────────────────────

static func remove_addon(root: String, addon_name: String, log: Callable) -> bool:
	var addons_dir := root + "/addons"
	var addon_path := addons_dir + "/" + addon_name

	if not DirAccess.dir_exists_absolute(addon_path):
		log.call("❌ Not found: " + addon_name)
		return false

	# Deps this addon uses
	var my_deps: Array[String] = []
	for line: String in _read(addon_path + "/DEPENDENCIES.txt").split("\n"):
		line = line.strip_edges()
		if line.begins_with("http"):
			my_deps.append(line.rstrip("/").get_file().replace(".git", ""))

	# Deps still needed by other addons
	var needed: Array[String] = []
	var dir := DirAccess.open(addons_dir)
	if dir:
		dir.list_dir_begin()
		var name := dir.get_next()
		while name != "":
			if dir.current_is_dir() and not name.begins_with(".") and name != addon_name:
				for line: String in _read(addons_dir + "/" + name + "/DEPENDENCIES.txt").split("\n"):
					line = line.strip_edges()
					if line.begins_with("http"):
						needed.append(line.rstrip("/").get_file().replace(".git", ""))
			name = dir.get_next()
		dir.list_dir_end()

	log.call("🗑️  Removing: " + addon_name)
	_rm_rf(addon_path)

	for dep: String in my_deps:
		if dep in needed:
			log.call("⏭️  Keeping: " + dep + " (used by others)")
		elif DirAccess.dir_exists_absolute(addons_dir + "/" + dep):
			log.call("🗑️  Removing orphaned dep: " + dep)
			_rm_rf(addons_dir + "/" + dep)

	log.call("✅ Cleanup complete.")
	return true

# ─── UPDATE PLUGIN ───────────────────────────────────────────────────────────

static func update_plugin(root: String, log: Callable) -> bool:
	log.call("⬆️  Pulling latest ChillCube Tools...")
	var code := _git(["pull", "--rebase", "origin", "main"], root, log)
	if code != OK:
		log.call("⚠️  Pull failed — resolve conflicts manually.")
		_git(["rebase", "--abort"], root, Callable())
		return false
	log.call("✅ Plugin updated! Restart Godot to apply changes.")
	return true

# ─── PUSH ALL ADDONS ─────────────────────────────────────────────────────────

static func push_all(root: String, log: Callable, exclude: Array[String] = [], on_pushed: Callable = Callable()) -> bool:
	var addons_dir := root + "/addons"
	if not DirAccess.dir_exists_absolute(addons_dir):
		log.call("❌ No addons/ directory.")
		return false

	log.call("🔍 Pre-scanning classes...")
	var class_to_repo := {}
	var class_to_addon := {}
	_prescan_classes(addons_dir, class_to_repo, class_to_addon)

	log.call("🔍 Pre-scanning reverse deps...")
	var dependents_of := {}
	_prescan_reverse_deps(addons_dir, dependents_of)

	var updated := 0
	var dir := DirAccess.open(addons_dir)
	if not dir:
		return false

	dir.list_dir_begin()
	var name := dir.get_next()
	while name != "":
		if dir.current_is_dir() and not name.begins_with("."):
			if name in exclude:
				log.call("⏭️  Skipping self: " + name)
				name = dir.get_next()
				continue
			var apath := addons_dir + "/" + name
			if DirAccess.dir_exists_absolute(apath + "/.git") and \
					FileAccess.file_exists(apath + "/plugin.cfg"):
				log.call("──────────────────────────")
				log.call("📦 Processing: " + name)
				if _process_one(root, name, class_to_repo, class_to_addon, dependents_of, log):
					updated += 1
					if on_pushed.is_valid():
						on_pushed.call(name)
		name = dir.get_next()
	dir.list_dir_end()

	log.call("──────────────────────────")
	log.call("🌳 Updating registry tree...")
	_update_tree(root, log)

	log.call("✅ Finished! %d updated." % updated)
	return true

static func _prescan_classes(addons_dir: String, class_to_repo: Dictionary, class_to_addon: Dictionary) -> void:
	var dir := DirAccess.open(addons_dir)
	if not dir:
		return
	dir.list_dir_begin()
	var name := dir.get_next()
	while name != "":
		if dir.current_is_dir() and not name.begins_with("."):
			var apath := addons_dir + "/" + name
			var url := git_remote(apath)
			if not url.is_empty():
				for gf: String in _find(apath, "*.gd"):
					for line: String in _read(gf).split("\n"):
						if line.begins_with("class_name "):
							var cname := line.replace("class_name ", "").strip_edges().split(" ")[0].split(":")[0]
							if not cname.is_empty():
								class_to_repo[cname] = url
								class_to_addon[cname] = name
		name = dir.get_next()
	dir.list_dir_end()

static func _prescan_reverse_deps(addons_dir: String, dependents_of: Dictionary) -> void:
	var dir := DirAccess.open(addons_dir)
	if not dir:
		return
	dir.list_dir_begin()
	var name := dir.get_next()
	while name != "":
		if dir.current_is_dir() and not name.begins_with("."):
			var apath := addons_dir + "/" + name
			var cfg := apath + "/plugin.cfg"
			var dep_file := apath + "/DEPENDENCIES.txt"
			if FileAccess.file_exists(cfg) and FileAccess.file_exists(dep_file):
				var info := parse_cfg(cfg)
				var depender_name: String = info.get("name", name)
				var depender_url := git_remote(apath)
				for line: String in _read(dep_file).split("\n"):
					line = line.strip_edges()
					if line.begins_with("http"):
						var clean := line.replace(".git", "")
						if clean not in dependents_of:
							dependents_of[clean] = []
						dependents_of[clean].append({"name": depender_name, "url": depender_url})
		name = dir.get_next()
	dir.list_dir_end()

static func _process_one(root: String, folder: String, c2r: Dictionary, c2a: Dictionary, deps_of: Dictionary, log: Callable) -> bool:
	var addons_dir := root + "/addons"
	var apath := addons_dir + "/" + folder
	var info := parse_cfg(apath + "/plugin.cfg")
	var a_name: String = info.get("name", folder)
	var a_desc: String = info.get("description", "")
	var a_author: String = info.get("author", "")
	var a_category: String = info.get("category", "Uncategorized")
	var year := str(Time.get_datetime_dict_from_system()["year"])
	var cur_url := git_remote(apath)

	# Recursive dep scan
	var auto_deps: Array[String] = []
	var processed := [folder]
	var queue := [folder]
	while not queue.is_empty():
		var cur: String = queue.pop_front()
		var words: Dictionary = {}
		var re := RegEx.new()
		re.compile("\\b[A-Z][A-Za-z0-9_]+\\b")
		for gf: String in _find(addons_dir + "/" + cur, "*.gd"):
			for m: RegExMatch in re.search_all(_read(gf)):
				words[m.get_string()] = true
		for word: String in words:
			var target_a: String = c2a.get(word, "")
			if not target_a.is_empty() and target_a != folder:
				var url: String = c2r.get(word, "")
				if not url.is_empty() and url not in auto_deps:
					auto_deps.append(url)
					if target_a not in processed:
						queue.append(target_a)
						processed.append(target_a)

	# Write auto deps back to DEPENDENCIES.txt so cloners can install them
	var dep_file := apath + "/DEPENDENCIES.txt"
	var dep_content := _read(dep_file)
	if dep_content.is_empty():
		dep_content = AUTO_MARKER + "\n\n" + MANUAL_MARKER + "\n"
	var manual_start := dep_content.find(MANUAL_MARKER)
	var auto_section := AUTO_MARKER + "\n"
	for u: String in auto_deps:
		auto_section += u + "\n"
	auto_section += "\n"
	dep_content = auto_section + (dep_content.substr(manual_start) if manual_start != -1 else MANUAL_MARKER + "\n")
	_write(dep_file, dep_content)

	# Manual deps
	var manual_deps: Array[String] = []
	var in_manual := false
	for line: String in _read(dep_file).split("\n"):
		if MANUAL_MARKER in line:
			in_manual = true
			continue
		if in_manual and line.strip_edges().begins_with("http"):
			manual_deps.append(line.strip_edges())

	# Used-by
	var used_by: Array = deps_of.get(cur_url, [])

	# Generate README
	var clone_cmd := "clone-gd-addon " + cur_url + ".git"
	_write(apath + "/README.md", _readme(a_name, a_desc, a_author, year, clone_cmd, auto_deps, manual_deps, used_by))

	# Generate DOCUMENTATION
	var new_doc := _generate_doc(apath, a_name, a_desc, folder, c2r, c2a, auto_deps)
	var doc_path := apath + "/DOCUMENTATION.md"
	var old_doc := _read(doc_path)
	# Compare without the date line
	var nd := new_doc.split("\n")
	var od := old_doc.split("\n")
	if nd.size() > 1: nd.remove_at(1)
	if od.size() > 1: od.remove_at(1)
	if "\n".join(PackedStringArray(nd)) != "\n".join(PackedStringArray(od)):
		_write(doc_path, new_doc)

	if not is_chillcube(cur_url):
		log.call("⏭️  Skipping push & registry — not a ChillCube addon.")
		return false

	# Registry sync
	if not cur_url.is_empty():
		_sync_registry(a_name, a_desc, a_category, cur_url, log)

	# Git commit & push
	var status_out := []
	OS.execute("git", PackedStringArray(["-C", apath, "status", "-s"]), status_out, true)
	if not status_out.is_empty() and not status_out[0].strip_edges().is_empty():
		_git(["add", "."], apath, log)
		_git(["commit", "-m", "docs: auto-sync v1.0.0"], apath, log)
		_git(["push", "origin", "main"], apath, log)
		return true
	log.call("✨ Nothing to update.")
	return false

# ─── README generation ───────────────────────────────────────────────────────

static func _readme(name: String, desc: String, author: String, year: String,
		clone_cmd: String, auto_deps: Array[String] = [], manual_deps: Array[String] = [],
		used_by: Array = []) -> String:
	var t := "# " + name + "\n\n" + desc + "\n\n"
	t += "## Installation\n\n"
	t += "Make sure to download the ChillCube Developer tools: https://github.com/ChillCube/ChillCube-Developer-Tools.git\n\n"
	t += "### Using the Godot Plugin\n"
	t += "Enable the **ChillCube Tools** plugin, then paste the repo URL into the Clone tab.\n\n"
	t += "### Linux / CLI\n"
	t += "```bash\n"
	t += (clone_cmd if not clone_cmd.is_empty() else "clone-gd-addon https://github.com/ChillCube/" + name + ".git") + "\n"
	t += "```\n\n"
	t += "## Documentation\nhttps://github.com/ChillCube/" + name + "/blob/main/DOCUMENTATION.md\n\n"
	t += "## Deinstallation\n"
	t += "Use the CC Tools panel in Godot, or run:\n"
	t += "```bash\nremove-gd-addon " + name + "\n```\n\n"
	t += "## For Developers\n```bash\npush-all-addons\n```\n"

	var all_deps := auto_deps.duplicate()
	for d: String in manual_deps:
		if d not in all_deps:
			all_deps.append(d)
	if not all_deps.is_empty():
		t += "\n## Dependencies\n\n"
		for url: String in all_deps:
			var dep_name := url.get_file().replace("Godot_", "")
			t += "- [%s](%s)\n" % [dep_name, url]

	if not used_by.is_empty():
		t += "\n## Used By\n%d other ChillCube addon(s) depend on this:\n\n" % used_by.size()
		for d: Dictionary in used_by:
			t += "- [%s](%s)\n" % [d.get("name", ""), d.get("url", "")]

	return t

# ─── DOCUMENTATION generation ────────────────────────────────────────────────

static func _generate_doc(apath: String, a_name: String, a_desc: String, folder: String,
		c2r: Dictionary, c2a: Dictionary, auto_deps: Array[String]) -> String:
	var doc := "# %s API Reference\n" % a_name
	doc += "Generated: %s\n\n%s\n" % [Time.get_date_string_from_system(), a_desc]

	if not auto_deps.is_empty():
		doc += "\n### 📦 Dependencies\n\n"
		doc += "| Source | Documentation | Repository |\n| :--- | :--- | :--- |\n"
		for url: String in auto_deps:
			var ref_name := url.get_file().replace("Godot_", "")
			doc += "| Code | [`%s`](%s/blob/main/DOCUMENTATION.md) | [Repo](%s) |\n" % [ref_name, url, url]
		doc += "\n---\n\n"

	for script: String in _find(apath, "*.gd"):
		var lines := _read(script).split("\n")
		var cname := ""
		var extends_val := ""
		for line: String in lines:
			if line.begins_with("class_name "):
				cname = line.replace("class_name ", "").strip_edges().split(" ")[0].split(":")[0]
			elif line.begins_with("extends "):
				extends_val = line.replace("extends ", "").strip_edges()
		if cname.is_empty():
			cname = script.get_file().get_basename()

		doc += "## Class: %s\n" % cname
		if not extends_val.is_empty():
			var link := ""
			if extends_val in c2r:
				if c2a.get(extends_val, "") == folder:
					link = "[%s](#class-%s)" % [extends_val, extends_val.to_lower()]
				else:
					link = "[%s](%s/blob/main/DOCUMENTATION.md)" % [extends_val, c2r[extends_val]]
			else:
				link = "[%s](https://docs.godotengine.org/en/stable/classes/class_%s.html)" % [extends_val, extends_val.to_lower()]
			doc += "**Inherits:** %s\n\n" % link
		else:
			doc += "\n"

		var exported := _parse_vars(lines, true)
		if not exported.is_empty():
			doc += "### ⚙️ Inspector Variables (Exported)\n| Property | Type | Default | Description |\n| :--- | :--- | :--- | :--- |\n"
			for v: Array in exported:
				doc += "| **%s** | `%s` | `%s` | %s |\n" % [v[0], v[1], v[2], v[3]]
			doc += "\n"

		var standard := _parse_vars(lines, false)
		if not standard.is_empty():
			doc += "### 💾 Class Variables (Standard)\n| Property | Type | Default | Description |\n| :--- | :--- | :--- | :--- |\n"
			for v: Array in standard:
				doc += "| **%s** | `%s` | `%s` | %s |\n" % [v[0], v[1], v[2], v[3]]
			doc += "\n"

		var sigs := _parse_signals(lines)
		if not sigs.is_empty():
			doc += "### 🔔 Signals\n| Signal | Arguments | Description |\n| :--- | :--- | :--- |\n"
			for s: Array in sigs:
				doc += "| **%s** | %s | %s |\n" % [s[0], s[1], s[2]]
			doc += "\n"

		var methods := _parse_methods(lines)
		if not methods.is_empty():
			doc += "### 🛠️ Methods\n| Method | Arguments | Returns | Description |\n| :--- | :--- | :--- | :--- |\n"
			for m: Array in methods:
				doc += "| **%s()** | %s | `%s` | %s |\n" % [m[0], m[1], m[2], m[3]]
			doc += "\n"

		doc += "---\n\n"
	return doc

static func _parse_vars(lines: PackedStringArray, exported: bool) -> Array:
	var result := []
	for line: String in lines:
		if "var" not in line or "##" not in line:
			continue
		if exported and "@export" not in line:
			continue
		if not exported and "@export" in line:
			continue
		var parts := line.split("##", true, 1)
		if parts.size() < 2:
			continue
		var desc := parts[1].strip_edges()
		var code := parts[0].strip_edges()
		var re := RegEx.new()
		re.compile("var\\s+(\\w+)")
		var vm := re.search(code)
		if not vm:
			continue
		var vname := vm.get_string(1)
		var vtype := "Variant"
		var type_re := RegEx.new()
		type_re.compile(":\\s*([A-Za-z_]\\w*)")
		var tm := type_re.search(code)
		if tm:
			vtype = tm.get_string(1)
		var vdefault := "-"
		if "=" in code:
			var def_re := RegEx.new()
			def_re.compile("=\\s*(.+?)(?:\\s*$)")
			var dm := def_re.search(parts[0])
			if dm:
				vdefault = dm.get_string(1).strip_edges()
		result.append([vname, vtype, vdefault, desc])
	return result

static func _parse_signals(lines: PackedStringArray) -> Array:
	var result := []
	for line: String in lines:
		if "signal " not in line or "##" not in line:
			continue
		var parts := line.split("##", true, 1)
		if parts.size() < 2:
			continue
		var desc := parts[1].strip_edges()
		var code := parts[0].strip_edges().replace("signal ", "").strip_edges()
		var sig_name := code
		var args := "-"
		if "(" in code:
			sig_name = code.split("(")[0]
			var raw := code.split("(")[1].replace(")", "").strip_edges()
			if not raw.is_empty():
				args = "`" + raw.replace(", ", "`<br>`") + "`"
		result.append([sig_name, args, desc])
	return result

static func _parse_methods(lines: PackedStringArray) -> Array:
	var result := []
	for line: String in lines:
		if "func " not in line or "##" not in line:
			continue
		var parts := line.split("##", true, 1)
		if parts.size() < 2:
			continue
		var desc := parts[1].strip_edges()
		var code := parts[0].strip_edges()
		var re := RegEx.new()
		re.compile("func\\s+(\\w+)\\(([^)]*)\\)")
		var fm := re.search(code)
		if not fm:
			continue
		var fname := fm.get_string(1)
		if fname.begins_with("_"):
			continue
		var raw_args := fm.get_string(2).strip_edges()
		var args := "`" + raw_args.replace(", ", "`<br>`") + "`" if not raw_args.is_empty() else "-"
		var ret := "void"
		if "->" in code:
			var rre := RegEx.new()
			rre.compile("->\\s*(\\w+)")
			var rm := rre.search(code)
			if rm:
				ret = rm.get_string(1)
		result.append([fname, args, ret, desc])
	return result

# ─── Registry ────────────────────────────────────────────────────────────────

static func _sync_registry(addon_name: String, addon_desc: String, addon_category: String, addon_url: String, log: Callable) -> void:
	var tmp := OS.get_temp_dir() + "/.cc_reg_" + str(int(Time.get_unix_time_from_system()))
	if _exec("git", ["clone", "--depth", "1", ORG_REPO, tmp], Callable()) != OK:
		log.call("⚠️  Registry clone failed (skipping).")
		return

	var rfile := tmp + "/ADDONS.md"
	var content := _read(rfile)
	if content.is_empty():
		content = "# 🧊 ChillCube Addon Registry\n\n## Uncategorized\n"

	if addon_url not in content:
		var entry := "* [%s](%s) - %s" % [addon_name, addon_url, addon_desc]
		var section := "## " + addon_category
		if section in content:
			content = content.replace(section + "\n", section + "\n" + entry + "\n")
		else:
			content += "\n" + section + "\n" + entry + "\n"
		_write(rfile, content)
		_exec("git", ["-C", tmp, "add", "ADDONS.md"], Callable())
		_exec("git", ["-C", tmp, "commit", "-m", "registry: add " + addon_name], Callable())
		_exec("git", ["-C", tmp, "push", "origin", "main"], Callable())
		log.call("📋 Registry updated: " + addon_name)
	_rm_rf(tmp)

static func _update_tree(root: String, log: Callable) -> void:
	var tmp := OS.get_temp_dir() + "/.cc_tree_" + str(int(Time.get_unix_time_from_system()))
	if _exec("git", ["clone", "--depth", "1", ORG_REPO, tmp], Callable()) != OK:
		log.call("⚠️  Registry clone failed, skipping tree update.")
		return

	var addons_dir := root + "/addons"
	var rfile := tmp + "/ADDONS.md"
	var content := _read(rfile)

	# Strip old tree block
	var s_mark := "<!-- DEPENDENCY-TREE-START -->"
	var e_mark := "<!-- DEPENDENCY-TREE-END -->"
	if s_mark in content:
		var si := content.find(s_mark)
		var ei := content.find(e_mark)
		if ei != -1:
			content = content.substr(0, si) + content.substr(ei + e_mark.length())

	# Collect nodes
	var nodes := {}  # id -> {label, url, indegree, size, internal}
	var dir := DirAccess.open(addons_dir)
	if dir:
		dir.list_dir_begin()
		var name := dir.get_next()
		while name != "":
			if dir.current_is_dir() and not name.begins_with("."):
				var cfg := addons_dir + "/" + name + "/plugin.cfg"
				if FileAccess.file_exists(cfg):
					var info := parse_cfg(cfg)
					var raw: String = info.get("name", name)
					var id := _make_id(raw)
					var url := git_remote(addons_dir + "/" + name)
					nodes[id] = {"label": _clean_label(raw), "url": url,
						"indegree": 0, "size": _find(addons_dir + "/" + name, "*.gd").size(), "internal": true}
			name = dir.get_next()
		dir.list_dir_end()

	# Collect edges
	var edges: Array[Array] = []
	var deps_map := {}  # from_id -> [to_ids]
	var has_edge := {}
	var dir2 := DirAccess.open(addons_dir)
	if dir2:
		dir2.list_dir_begin()
		var name2 := dir2.get_next()
		while name2 != "":
			if dir2.current_is_dir() and not name2.begins_with("."):
				var cfg := addons_dir + "/" + name2 + "/plugin.cfg"
				var dep_file := addons_dir + "/" + name2 + "/DEPENDENCIES.txt"
				if FileAccess.file_exists(cfg) and FileAccess.file_exists(dep_file):
					var info := parse_cfg(cfg)
					var from_id := _make_id(info.get("name", name2))
					for line: String in _read(dep_file).split("\n"):
						line = line.strip_edges()
						if line.begins_with("http"):
							var dep_repo := line.rstrip("/").get_file().replace(".git", "")
							var to_id := _make_id(dep_repo)
							if from_id.is_empty() or to_id.is_empty():
								continue
							if to_id not in nodes:
								nodes[to_id] = {"label": _clean_label(dep_repo), "url": line.replace(".git", ""),
									"indegree": 0, "size": 0, "internal": false}
							nodes[to_id]["indegree"] = int(nodes[to_id]["indegree"]) + 1
							has_edge[from_id] = true
							has_edge[to_id] = true
							edges.append([from_id, to_id])
							if from_id not in deps_map:
								deps_map[from_id] = []
							deps_map[from_id].append(to_id)
			name2 = dir2.get_next()
		dir2.list_dir_end()

	# Topological layers
	var layers := {}
	for id: String in has_edge:
		if id not in deps_map or (deps_map[id] as Array).is_empty():
			layers[id] = 0
	var changed := true
	while changed:
		changed = false
		for id: String in has_edge:
			if id in layers:
				continue
			var all_ok := true
			var max_l := -1
			for dep: String in deps_map.get(id, []):
				if dep not in layers:
					all_ok = false
					break
				if int(layers[dep]) > max_l:
					max_l = int(layers[dep])
			if all_ok:
				layers[id] = max_l + 1
				changed = true
	for id: String in has_edge:
		if id not in layers:
			layers[id] = 0

	# Score
	var score := 0
	for id: String in nodes:
		var n: Dictionary = nodes[id]
		score += int(n.get("size", 0)) * 10 + int(n.get("indegree", 0)) * 50 + int(layers.get(id, 0)) * 20

	# Max layer
	var max_layer := 0
	for id: String in has_edge:
		if int(layers.get(id, 0)) > max_layer:
			max_layer = int(layers.get(id, 0))

	# Build Mermaid
	var m := "\n" + s_mark + "\n## 🌳 Dependency Tree\n\n"
	m += "```mermaid\n"
	m += "%%{init: {\"flowchart\": {\"curve\": \"linear\"}}}%%\n"
	m += "flowchart BT\n"
	m += "    classDef core  fill:#4a9eff,stroke:#2471d4,color:#fff\n"
	m += "    classDef shared fill:#a29bfe,stroke:#6c5ce7,color:#fff\n"
	m += "    classDef external fill:#fd9644,stroke:#e67e22,color:#fff\n\n"

	for l in range(max_layer + 1):
		var ids: Array[String] = []
		for id: String in has_edge:
			if int(layers.get(id, 0)) == l:
				ids.append(id)
		ids.sort()
		if ids.is_empty():
			continue
		m += '    subgraph Layer_%d["%s"]\n' % [l, "🧱 Layer 0 — Foundation" if l == 0 else "Layer %d" % l]
		for id: String in ids:
			m += '        %s["%s"]\n' % [id, (nodes.get(id, {}) as Dictionary).get("label", id)]
		m += "    end\n"
	m += "\n"

	for edge: Array in edges:
		var f: String = edge[0]
		var t: String = edge[1]
		if not f.is_empty() and not t.is_empty():
			m += "    %s --> %s\n" % [t, f]
	m += "\n"

	var edge_ids := has_edge.keys()
	edge_ids.sort()
	for id: String in edge_ids:
		var n: Dictionary = nodes.get(id, {})
		if not bool(n.get("internal", false)):
			m += "    class %s external\n" % id
		else:
			var deg := int(n.get("indegree", 0))
			if deg >= 2:
				m += "    class %s core\n" % id
			elif deg == 1:
				m += "    class %s shared\n" % id
	m += "\n"

	for id: String in edge_ids:
		var url: String = (nodes.get(id, {}) as Dictionary).get("url", "")
		if not url.is_empty():
			m += '    click %s href "%s" _blank\n' % [id, url]
	m += "```\n"

	# Standalone
	var standalone: Array[String] = []
	for id: String in nodes:
		if id not in has_edge:
			var n: Dictionary = nodes[id]
			var label: String = n.get("label", id)
			var url: String = n.get("url", "")
			standalone.append("[%s](%s)" % [label, url] if not url.is_empty() else label)
	if not standalone.is_empty():
		m += "\n**Standalone addons:** " + " · ".join(PackedStringArray(standalone)) + "\n"

	m += "\n**🏆 Progress Score: %d pts** — _+10 per .gd file · +50 per module that depends on you · +20 per dependency layer_\n" % score
	m += e_mark

	_write(rfile, content.rstrip("\n") + m)
	_exec("git", ["-C", tmp, "add", "ADDONS.md"], Callable())
	_exec("git", ["-C", tmp, "commit", "-m", "registry: update dependency tree"], Callable())
	_exec("git", ["-C", tmp, "push", "origin", "main"], Callable())
	_rm_rf(tmp)

# ─── CC TOOLS DATA (stored in vault under _cc_tools/) ───────────────────────

const CC_DATA_DIR := "_cc_tools"

static func cc_data_push(data: Dictionary, log: Callable) -> bool:
	var tmp := OS.get_temp_dir() + "/.cc_data_" + str(int(Time.get_unix_time_from_system()))
	if _git(["clone", "--depth=1", "--quiet", VAULT_SSH, tmp], "", log) != OK:
		log.call("❌ Could not reach vault.")
		_rm_rf(tmp)
		return false
	DirAccess.make_dir_recursive_absolute(tmp + "/" + CC_DATA_DIR)
	for fname: String in data:
		_write(tmp + "/" + CC_DATA_DIR + "/" + fname, data[fname])
	_git(["add", CC_DATA_DIR], tmp, Callable())
	if _git(["commit", "-m", "cc-tools: sync data"], tmp, Callable()) != OK:
		_rm_rf(tmp)
		return true
	var ok := _git(["push", "origin", "HEAD"], tmp, Callable()) == OK
	_rm_rf(tmp)
	log.call("✅ Synced to vault!" if ok else "❌ Push failed.")
	return ok

static func cc_data_read(cache_dir: String, fname: String) -> String:
	var out := []
	OS.execute("git", PackedStringArray(["-C", cache_dir, "show",
		"origin/main:" + CC_DATA_DIR + "/" + fname]), out, true)
	return out[0] if not out.is_empty() else ""

# ─── FILE VAULT ──────────────────────────────────────────────────────────────
# Uses a metadata-only clone (no file blobs) for browsing, then extracts
# individual files on demand. Upload uses a temp shallow clone.

const VAULT_SSH := "git@github.com:ChillCube/vault.git"
const VAULT_REPO := "ChillCube/vault"

# Fetch or create a lightweight metadata cache (tree objects only, no blobs).
static func vault_refresh(cache_dir: String, log: Callable) -> bool:
	if DirAccess.dir_exists_absolute(cache_dir + "/.git"):
		log.call("🔄 Refreshing file list...")
		_git(["fetch", "--quiet", "origin"], cache_dir, log)
		return true
	_rm_rf(cache_dir)
	log.call("📋 Fetching vault file list...")
	# --no-checkout --filter=blob:none: downloads only tree objects, no file contents
	if _git(["clone", "--no-checkout", "--filter=blob:none", "--quiet", VAULT_SSH, cache_dir], "", log) == OK:
		log.call("✅ Vault ready.")
		return true
	log.call("❌ Could not reach ChillCube/vault.")
	log.call("   Make sure the repo exists at github.com/ChillCube/vault (private).")
	return false

# Return every file path stored in the vault (flat list, from tree metadata only).
static func vault_list_files(cache_dir: String) -> Array[String]:
	var output := []
	OS.execute("git", PackedStringArray(["-C", cache_dir, "ls-tree", "-r", "--name-only", "origin/main"]), output, true)
	var result: Array[String] = []
	if output.is_empty():
		return result
	for line: String in output[0].split("\n"):
		var l := line.strip_edges()
		if not l.is_empty():
			result.append(l)
	return result

# Extract a single file from the vault without checking out anything else.
static func vault_download_file(cache_dir: String, remote_rel: String, local_dest: String, log: Callable) -> bool:
	var dest_dir: String
	if local_dest.begins_with("res://") or local_dest.begins_with("user://"):
		dest_dir = ProjectSettings.globalize_path(local_dest).rstrip("/")
	else:
		dest_dir = local_dest.rstrip("/")
	DirAccess.make_dir_recursive_absolute(dest_dir)
	var dest_file := dest_dir + "/" + remote_rel.get_file()
	log.call("⬇️  Extracting " + remote_rel.get_file() + "...")
	# Pipe git-show into the destination file so binary files are handled correctly
	var safe_cache := cache_dir.replace("'", "'\"'\"'")
	var safe_ref  := remote_rel.lstrip("/").replace("'", "'\"'\"'")
	var safe_dest := dest_file.replace("'", "'\"'\"'")
	var cmd := "git -C '%s' show 'origin/main:%s' > '%s'" % [safe_cache, safe_ref, safe_dest]
	var out := []
	var code := OS.execute("bash", PackedStringArray(["-c", cmd]), out, true)
	if code != OK:
		log.call("❌ Failed to extract file.")
		if not out.is_empty(): log.call(out[0])
		return false
	log.call("✅ Saved to " + dest_file)
	return true

# Upload a local file into the vault via a temporary shallow clone.
static func vault_upload_file(local_file: String, remote_dir: String, log: Callable) -> bool:
	var tmp := OS.get_temp_dir() + "/.cc_vaultup_" + str(int(Time.get_unix_time_from_system()))
	log.call("📥 Preparing upload (shallow clone)...")
	if _git(["clone", "--depth=1", "--quiet", VAULT_SSH, tmp], "", log) != OK:
		log.call("❌ Could not clone vault.")
		_rm_rf(tmp)
		return false
	var rdir := remote_dir.strip_edges().lstrip("/").rstrip("/")
	var dest_folder := tmp + ("/" + rdir if not rdir.is_empty() else "")
	DirAccess.make_dir_recursive_absolute(dest_folder)
	var filename := local_file.get_file()
	_exec("cp", ["-f", local_file, dest_folder + "/" + filename], log)
	log.call("📦 Committing " + filename + "...")
	_git(["add", "."], tmp, log)
	if _git(["commit", "-m", "vault: upload " + filename], tmp, log) != OK:
		log.call("✨ File unchanged — nothing to push.")
		_rm_rf(tmp)
		return true
	log.call("⬆️  Pushing...")
	var ok := _git(["push", "origin", "main"], tmp, log) == OK
	_rm_rf(tmp)
	log.call("✅ Uploaded " + filename if ok else "⚠️  Push failed.")
	return ok

static func vault_move_file(src_rel: String, dest_rel: String, log: Callable) -> bool:
	var tmp := OS.get_temp_dir() + "/.cc_vaultmv_" + str(int(Time.get_unix_time_from_system()))
	log.call("📥 Preparing move (shallow clone)...")
	if _git(["clone", "--depth=1", "--quiet", VAULT_SSH, tmp], "", log) != OK:
		log.call("❌ Could not clone vault.")
		_rm_rf(tmp)
		return false
	var src := src_rel.strip_edges().lstrip("/")
	var dest := dest_rel.strip_edges().lstrip("/")
	var dest_dir := tmp + "/" + dest.get_base_dir()
	if dest.get_base_dir() != ".":
		DirAccess.make_dir_recursive_absolute(dest_dir)
	if _git(["mv", src, dest], tmp, log) != OK:
		log.call("❌ Move failed — file may not exist at that path.")
		_rm_rf(tmp)
		return false
	_git(["add", "."], tmp, log)
	if _git(["commit", "-m", "vault: move " + src.get_file() + " → " + dest], tmp, log) != OK:
		log.call("✨ Nothing to commit.")
		_rm_rf(tmp)
		return true
	var ok := _git(["push", "origin", "main"], tmp, log) == OK
	_rm_rf(tmp)
	log.call("✅ Moved!" if ok else "⚠️  Push failed.")
	return ok

static func vault_delete_file(remote_rel: String, log: Callable) -> bool:
	var tmp := OS.get_temp_dir() + "/.cc_vaultdel_" + str(int(Time.get_unix_time_from_system()))
	if _git(["clone", "--depth=1", "--quiet", VAULT_SSH, tmp], "", log) != OK:
		log.call("❌ Could not clone assets.")
		_rm_rf(tmp)
		return false
	var rpath := remote_rel.strip_edges().lstrip("/")
	var full := tmp + "/" + rpath
	if not FileAccess.file_exists(full):
		log.call("❌ File not found.")
		_rm_rf(tmp)
		return false
	DirAccess.remove_absolute(full)
	_git(["add", "-A"], tmp, Callable())
	_git(["commit", "-m", "assets: delete " + rpath], tmp, Callable())
	var ok := _git(["push", "origin", "HEAD"], tmp, Callable()) == OK
	_rm_rf(tmp)
	log.call("✅ Deleted." if ok else "❌ Push failed.")
	return ok

static func vault_mkdir(dir_path: String, log: Callable) -> bool:
	var tmp := OS.get_temp_dir() + "/.cc_vaultmkdir_" + str(int(Time.get_unix_time_from_system()))
	log.call("📥 Preparing (shallow clone)...")
	if _git(["clone", "--depth=1", "--quiet", VAULT_SSH, tmp], "", log) != OK:
		log.call("❌ Could not clone vault.")
		_rm_rf(tmp)
		return false
	var rdir := dir_path.strip_edges().lstrip("/").rstrip("/")
	DirAccess.make_dir_recursive_absolute(tmp + "/" + rdir)
	_write(tmp + "/" + rdir + "/.gitkeep", "")
	_git(["add", "."], tmp, log)
	if _git(["commit", "-m", "vault: create directory " + rdir], tmp, log) != OK:
		log.call("✨ Directory already exists.")
		_rm_rf(tmp)
		return true
	var ok := _git(["push", "origin", "main"], tmp, log) == OK
	_rm_rf(tmp)
	log.call("✅ Created " + rdir if ok else "⚠️  Push failed.")
	return ok

static func _make_id(s: String) -> String:
	return s.to_lower().replace(" ", "_").replace("-", "_")

static func _clean_label(s: String) -> String:
	return s.replace("Godot_", "").replace("_", " ")

# ─── API CONTRACT ────────────────────────────────────────────────────────────

# Scan an addon's .gd files and return every public symbol:
# public func (not starting with _), @export var, and signal.
static func extract_api(addon_path: String) -> Array:
	var result: Array = []
	var func_re := RegEx.new()
	func_re.compile("^(?:static\\s+)?func\\s+(\\w+)\\s*\\(([^)]*)\\)(?:\\s*->\\s*(\\w+))?")
	var export_re := RegEx.new()
	export_re.compile("^@export\\s+var\\s+(\\w+)(?:\\s*:\\s*(\\w+))?")
	var signal_re := RegEx.new()
	signal_re.compile("^signal\\s+(\\w+)(?:\\s*\\(([^)]*)\\))?")
	for gf: String in _find(addon_path, "*.gd"):
		var rel: String = gf.replace(addon_path + "/", "")
		for line: String in _read(gf).split("\n"):
			var t: String = line.strip_edges()
			if t.is_empty() or t.begins_with("#"):
				continue
			var fm := func_re.search(t)
			if fm:
				var fname: String = fm.get_string(1)
				if not fname.begins_with("_"):
					var args: String = fm.get_string(2).strip_edges()
					var ret: String = fm.get_string(3).strip_edges()
					if ret.is_empty():
						ret = "void"
					result.append({"kind": "func", "name": fname,
						"signature": "(%s) -> %s" % [args, ret], "file": rel})
				continue
			var em := export_re.search(t)
			if em:
				var vname: String = em.get_string(1)
				var vtype: String = em.get_string(2).strip_edges()
				if vtype.is_empty():
					vtype = "Variant"
				result.append({"kind": "export_var", "name": vname, "type": vtype, "file": rel})
				continue
			var sm := signal_re.search(t)
			if sm:
				var sname: String = sm.get_string(1)
				var sargs: String = sm.get_string(2).strip_edges()
				result.append({"kind": "signal", "name": sname, "args": sargs, "file": rel})
	return result

# ─── AUTH ─────────────────────────────────────────────────────────────────────

const AUTH_SSH := "git@github.com:ChillCube/cc-auth.git"

static func auth_hash(password: String) -> String:
	var ctx := HashingContext.new()
	ctx.start(HashingContext.HASH_SHA256)
	ctx.update(password.to_utf8_buffer())
	return ctx.finish().hex_encode()

static func _auth_tmp() -> String:
	return OS.get_temp_dir() + "/.cc_auth_" + str(int(Time.get_unix_time_from_system()))

static func _auth_load(tmp: String) -> Dictionary:
	var parsed: Variant = JSON.parse_string(_read(tmp + "/accounts.json"))
	return parsed if parsed is Dictionary else {"users": []}

static func _auth_save(tmp: String, data: Dictionary) -> void:
	_write(tmp + "/accounts.json", JSON.stringify(data, "\t") + "\n")

static func _auth_clone(log: Callable) -> String:
	var tmp := _auth_tmp()
	if _git(["clone", "--depth=1", "--quiet", AUTH_SSH, tmp], "", Callable()) != OK:
		log.call("❌ Cannot reach auth server. Check SSH/git access.")
		return ""
	return tmp

static func auth_verify(username: String, password: String, log: Callable) -> Dictionary:
	log.call("🔄 Connecting...")
	var tmp := _auth_clone(log)
	if tmp.is_empty():
		return {}
	var users: Array = _auth_load(tmp).get("users", [])
	_rm_rf(tmp)
	var h := auth_hash(password)
	for u: Dictionary in users:
		if (u.get("username", "") as String).to_lower() == username.to_lower():
			if u.get("password_hash", "") == h:
				if u.get("approved", false):
					return u
				log.call("⏳ Account pending approval by the leader.")
				return {}
	log.call("❌ Invalid username or password.")
	return {}

static func auth_register(username: String, github_username: String, password: String, log: Callable) -> bool:
	log.call("🔄 Connecting...")
	var tmp := _auth_clone(log)
	if tmp.is_empty():
		return false
	var data := _auth_load(tmp)
	var users: Array = data.get("users", [])
	for u: Dictionary in users:
		if (u.get("username", "") as String).to_lower() == username.to_lower():
			log.call("❌ Username already taken.")
			_rm_rf(tmp)
			return false
	users.append({"username": username, "github_username": github_username,
		"password_hash": auth_hash(password), "role": "member", "approved": false})
	data["users"] = users
	_auth_save(tmp, data)
	_git(["add", "accounts.json"], tmp, Callable())
	_git(["commit", "-m", "auth: register " + username], tmp, Callable())
	var ok := _git(["push", "origin", "main"], tmp, Callable()) == OK
	_rm_rf(tmp)
	log.call("✅ Account created! Waiting for leader approval." if ok else "❌ Push failed — do you have collaborator access to cc-auth?")
	return ok

static func auth_change_password(username: String, old_pw: String, new_pw: String, log: Callable) -> bool:
	log.call("🔄 Connecting...")
	var tmp := _auth_clone(log)
	if tmp.is_empty():
		return false
	var data := _auth_load(tmp)
	var users: Array = data.get("users", [])
	var found := false
	for u: Dictionary in users:
		if (u.get("username", "") as String).to_lower() == username.to_lower():
			if u.get("password_hash", "") != auth_hash(old_pw):
				log.call("❌ Current password is incorrect.")
				_rm_rf(tmp)
				return false
			u["password_hash"] = auth_hash(new_pw)
			found = true
			break
	if not found:
		_rm_rf(tmp)
		log.call("❌ User not found.")
		return false
	data["users"] = users
	_auth_save(tmp, data)
	_git(["add", "accounts.json"], tmp, Callable())
	_git(["commit", "-m", "auth: change password for " + username], tmp, Callable())
	var ok := _git(["push", "origin", "main"], tmp, Callable()) == OK
	_rm_rf(tmp)
	log.call("✅ Password changed!" if ok else "❌ Push failed.")
	return ok

static func auth_approve(approver: String, target: String, log: Callable) -> bool:
	var tmp := _auth_clone(log)
	if tmp.is_empty():
		return false
	var data := _auth_load(tmp)
	var users: Array = data.get("users", [])
	var found := false
	var gh_user := ""
	for u: Dictionary in users:
		if (u.get("username", "") as String).to_lower() == target.to_lower():
			u["approved"] = true
			found = true
			gh_user = u.get("github_username", "")
			break
	if not found:
		log.call("❌ User not found.")
		_rm_rf(tmp)
		return false
	data["users"] = users
	_auth_save(tmp, data)
	_git(["add", "accounts.json"], tmp, Callable())
	_git(["commit", "-m", "auth: " + approver + " approved " + target], tmp, Callable())
	var ok := _git(["push", "origin", "main"], tmp, Callable()) == OK
	_rm_rf(tmp)
	if ok and not gh_user.is_empty():
		log.call("🔑 Granting GitHub access to " + gh_user + "...")
		for repo in ["ChillCube/vault", "ChillCube/cc-auth"]:
			_gh(["api", "-X", "PUT", "repos/" + repo + "/collaborators/" + gh_user,
				"--field", "permission=push"], log)
	log.call("✅ Approved: " + target if ok else "❌ Push failed.")
	return ok

static func auth_fetch_pending(log: Callable) -> Array:
	var tmp := _auth_clone(log)
	if tmp.is_empty():
		return []
	var users: Array = _auth_load(tmp).get("users", [])
	_rm_rf(tmp)
	var result: Array = []
	for u: Dictionary in users:
		if not u.get("approved", false):
			result.append(u.get("username", ""))
	return result

static func auth_fetch_all(log: Callable) -> Array:
	var tmp := _auth_clone(log)
	if tmp.is_empty():
		return []
	var users: Array = _auth_load(tmp).get("users", [])
	_rm_rf(tmp)
	return users

static func auth_remove(approver: String, target: String, log: Callable) -> bool:
	var tmp := _auth_clone(log)
	if tmp.is_empty():
		return false
	var data := _auth_load(tmp)
	var users: Array = data.get("users", [])
	var gh_user := ""
	var new_users: Array = []
	for u: Dictionary in users:
		if (u.get("username", "") as String).to_lower() == target.to_lower():
			gh_user = u.get("github_username", "")
		else:
			new_users.append(u)
	if new_users.size() == users.size():
		log.call("❌ User not found.")
		_rm_rf(tmp)
		return false
	data["users"] = new_users
	_auth_save(tmp, data)
	_git(["add", "accounts.json"], tmp, Callable())
	_git(["commit", "-m", "auth: " + approver + " removed " + target], tmp, Callable())
	var ok := _git(["push", "origin", "main"], tmp, Callable()) == OK
	_rm_rf(tmp)
	if ok and not gh_user.is_empty():
		log.call("🔑 Revoking GitHub access from " + gh_user + "...")
		for repo in ["ChillCube/vault", "ChillCube/cc-auth"]:
			_gh(["api", "-X", "DELETE", "repos/" + repo + "/collaborators/" + gh_user], log)
	log.call("✅ Removed: " + target if ok else "❌ Push failed.")
	return ok

static func auth_change_username(username: String, new_name: String, log: Callable) -> String:
	log.call("🔄 Connecting...")
	var tmp := _auth_clone(log)
	if tmp.is_empty():
		return ""
	var data := _auth_load(tmp)
	var users: Array = data.get("users", [])
	for u: Dictionary in users:
		if (u.get("username", "") as String).to_lower() == new_name.to_lower():
			log.call("❌ Username already taken.")
			_rm_rf(tmp)
			return ""
	var found := false
	for u: Dictionary in users:
		if (u.get("username", "") as String).to_lower() == username.to_lower():
			u["username"] = new_name
			found = true
			break
	if not found:
		log.call("❌ User not found.")
		_rm_rf(tmp)
		return ""
	data["users"] = users
	_auth_save(tmp, data)
	_git(["add", "accounts.json"], tmp, Callable())
	_git(["commit", "-m", "auth: rename " + username + " -> " + new_name], tmp, Callable())
	var ok := _git(["push", "origin", "main"], tmp, Callable()) == OK
	_rm_rf(tmp)
	log.call("✅ Username changed!" if ok else "❌ Push failed.")
	return new_name if ok else ""

static func auth_bootstrap(log: Callable) -> bool:
	log.call("🌐 Creating ChillCube/cc-auth repo...")
	_gh(["repo", "create", "ChillCube/cc-auth", "--private",
		"--description", "ChillCube Tools authentication (private)"], log)
	var tmp := _auth_tmp()
	DirAccess.make_dir_recursive_absolute(tmp)
	_git(["init", "-q"], tmp, log)
	_git(["branch", "-m", "main"], tmp, log)
	var initial := {"users": [{"username": "IceCubeMaker",
		"password_hash": auth_hash("12345"), "role": "leader", "approved": true}]}
	_write(tmp + "/accounts.json", JSON.stringify(initial, "\t") + "\n")
	_write(tmp + "/README.md", "# ChillCube Auth\nPrivate — do not share.\n")
	_git(["add", "."], tmp, log)
	_git(["commit", "-m", "auth: initialize with IceCubeMaker"], tmp, log)
	_git(["remote", "add", "origin", AUTH_SSH], tmp, log)
	var ok := _git(["push", "-u", "origin", "main"], tmp, log) == OK
	_rm_rf(tmp)
	log.call("✅ Auth repo ready! IceCubeMaker / 12345" if ok else "❌ Push failed.")
	return ok
