@tool
extends RefCounted

# ─── Embedded assets ────────────────────────────────────────────────────────

const BOOST_LICENSE := """Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
"""

const AUTO_MARKER := "# --- Automated Dependencies (Managed by Script) ---"
const MANUAL_MARKER := "# --- Manually Add Dependencies Here  ---"
const ORG_REPO := "https://github.com/ChillCube/.github.git"

# ─── Low-level helpers ───────────────────────────────────────────────────────

static func _exec(cmd: String, args: Array, log: Callable) -> int:
	var psa := PackedStringArray()
	for a in args:
		psa.append(str(a))
	var output := []
	var code := OS.execute(cmd, psa, output, true)
	if log.is_valid() and not output.is_empty():
		for line: String in output[0].split("\n"):
			if not line.strip_edges().is_empty():
				log.call(line)
	return code

static func _git(args: Array, cwd: String, log: Callable) -> int:
	var full := ["-C", cwd] + args if not cwd.is_empty() else args
	return _exec("git", full, log)

static func _read(path: String) -> String:
	if not FileAccess.file_exists(path):
		return ""
	var f := FileAccess.open(path, FileAccess.READ)
	if not f:
		return ""
	var s := f.get_as_text()
	f.close()
	return s

static func _write(path: String, content: String) -> bool:
	var f := FileAccess.open(path, FileAccess.WRITE)
	if not f:
		return false
	f.store_string(content)
	f.close()
	return true

static func _rm_rf(path: String) -> void:
	_exec("rm", ["-rf", path], Callable())

static func _mv(from: String, to: String) -> void:
	_exec("mv", [from, to], Callable())

static func _find(base: String, pattern: String) -> Array[String]:
	var result: Array[String] = []
	var dir := DirAccess.open(base)
	if not dir:
		return result
	dir.list_dir_begin()
	var name := dir.get_next()
	while name != "":
		if not name.begins_with("."):
			var full := base + "/" + name
			if dir.current_is_dir():
				result.append_array(_find(full, pattern))
			elif _match(name, pattern):
				result.append(full)
		name = dir.get_next()
	dir.list_dir_end()
	return result

static func _match(name: String, pattern: String) -> bool:
	if not pattern.contains("*"):
		return name == pattern
	var parts := pattern.split("*", false)
	if parts.size() == 2:
		return name.begins_with(parts[0]) and name.ends_with(parts[1])
	return name == pattern

# ─── Addon metadata ──────────────────────────────────────────────────────────

static func list_addons(project_root: String) -> Array[String]:
	var result: Array[String] = []
	var dir := DirAccess.open(project_root + "/addons")
	if not dir:
		return result
	dir.list_dir_begin()
	var name := dir.get_next()
	while name != "":
		if dir.current_is_dir() and not name.begins_with("."):
			if FileAccess.file_exists(project_root + "/addons/" + name + "/plugin.cfg"):
				result.append(name)
		name = dir.get_next()
	dir.list_dir_end()
	return result

static func parse_cfg(path: String) -> Dictionary:
	var out := {"name": "", "description": "", "author": "", "version": "0.1.0"}
	for line: String in _read(path).split("\n"):
		for key in out.keys():
			if line.begins_with(key + "="):
				var val := line.split("=", true, 1)[1].strip_edges()
				if val.begins_with('"') and val.ends_with('"'):
					val = val.substr(1, val.length() - 2)
				out[key] = val
	return out

static func git_remote(addon_path: String) -> String:
	var output := []
	OS.execute("git", PackedStringArray(["-C", addon_path, "remote", "get-url", "origin"]), output, true)
	if output.is_empty():
		return ""
	var url: String = output[0].strip_edges()
	url = url.replace(".git", "")
	url = url.replace("git@github.com:", "https://github.com/")
	return url

# ─── CREATE ADDON ────────────────────────────────────────────────────────────

static func create_addon(root: String, addon_name: String, desc: String, author: String, create_gh: bool, log: Callable) -> bool:
	var safe := addon_name.replace(" ", "_")
	var target := root + "/addons/" + safe
	log.call("📂 Creating: " + target)

	if DirAccess.dir_exists_absolute(target):
		log.call("❌ Folder already exists: " + target)
		return false

	if DirAccess.make_dir_recursive_absolute(target) != OK:
		log.call("❌ Could not create directory.")
		return false

	log.call("🔧 Initializing Git...")
	_git(["init", "-q"], target, log)
	_git(["branch", "-m", "main"], target, log)

	_write(target + "/.gitignore", ".godot/\n*.import/\n*.tmp\n")
	_write(target + "/DEPENDENCIES.txt", AUTO_MARKER + "\n\n" + MANUAL_MARKER + "\n")

	var cfg := "[plugin]\nname=\"%s\"\ndescription=\"%s\"\nauthor=\"%s\"\nversion=\"0.1.0\"\nscript=\"\"\n" \
		% [addon_name, desc, author]
	_write(target + "/plugin.cfg", cfg)

	log.call("⚖️  Writing LICENSE...")
	_write(target + "/LICENSE", BOOST_LICENSE)

	log.call("📝 Generating README...")
	var year := str(Time.get_datetime_dict_from_system()["year"])
	_write(target + "/README.md", _readme(safe, desc, author, year, ""))

	log.call("📦 Initial commit...")
	_git(["add", "."], target, log)
	_git(["commit", "-m", "initial: initialize " + addon_name + " as a ChillCube addon"], target, log)

	if create_gh:
		log.call("🌐 Creating GitHub repo: ChillCube/" + safe)
		var code := _exec("gh", ["repo", "create", "ChillCube/" + safe,
			"--public", "--source=" + target, "--remote=origin", "--push"], log)
		if code != OK:
			log.call("⚠️  GitHub creation failed (is gh CLI authenticated?)")

	log.call("✅ Done! addons/" + safe)
	return true

# ─── CLONE ADDON ─────────────────────────────────────────────────────────────

static func clone_addon(root: String, repo_url: String, log: Callable) -> bool:
	var addons_dir := root + "/addons"
	DirAccess.make_dir_recursive_absolute(addons_dir)

	var tmp := OS.get_temp_dir() + "/.cc_clone_" + str(int(Time.get_unix_time_from_system()))
	log.call("📥 Cloning: " + repo_url)

	if _git(["clone", "--quiet", repo_url, tmp], "", log) != OK:
		log.call("❌ Clone failed.")
		return false

	var installed: Array[String] = []
	var cfgs := _find(tmp, "plugin.cfg")

	if cfgs.is_empty():
		var aname := repo_url.get_file().replace(".git", "")
		var target := addons_dir + "/" + aname
		log.call("📦 Installing (no plugin.cfg): " + aname)
		_mv(tmp, target)
		installed.append(target)
	else:
		for cfg_path: String in cfgs:
			var addon_dir := cfg_path.get_base_dir()
			if addon_dir == tmp:
				var aname := repo_url.get_file().replace(".git", "")
				var target := addons_dir + "/" + aname
				log.call("📦 Installing (repo root): " + aname)
				_mv(tmp, target)
				installed.append(target)
				break
			else:
				var aname := addon_dir.get_file()
				var target := addons_dir + "/" + aname
				log.call("📦 Installing: " + aname)
				_mv(addon_dir, target)
				_git(["init", "-q"], target, log)
				_git(["remote", "add", "origin", repo_url], target, log)
				installed.append(target)
	_rm_rf(tmp)

	for addon_path: String in installed:
		for cfg: String in _find(addon_path, "plugin.cfg"):
			_enable_plugin(root, cfg.replace(root + "/", ""), log)

	_install_deps(root, installed, log)
	log.call("✅ Done!")
	return true

static func _install_deps(root: String, installed: Array[String], log: Callable) -> void:
	var addons_dir := root + "/addons"
	var class_url := _build_class_map(addons_dir)

	for addon_path: String in installed:
		var dep_file := addon_path + "/DEPENDENCIES.txt"
		if not FileAccess.file_exists(dep_file):
			_write(dep_file, AUTO_MARKER + "\n\n" + MANUAL_MARKER + "\n")

		var self_url := git_remote(addon_path)
		var existing := _read(dep_file)
		var found: Array[String] = []

		var re := RegEx.new()
		re.compile("\\b[A-Z][A-Za-z0-9_]+\\b")
		for gf: String in _find(addon_path, "*.gd"):
			for m: RegExMatch in re.search_all(_read(gf)):
				var word := m.get_string()
				if word in class_url:
					var url: String = class_url[word]
					if url != self_url and url not in existing and url not in found:
						found.append(url)
						log.call("🔍 Auto-dep: " + url.get_file())

		if not found.is_empty():
			var block := AUTO_MARKER + "\n"
			for u: String in found:
				block += u + "\n"
			existing = existing.replace(AUTO_MARKER + "\n", block)
			_write(dep_file, existing)

	# Recursive install
	for dep_file: String in _find(addons_dir, "DEPENDENCIES.txt"):
		for line: String in _read(dep_file).split("\n"):
			line = line.strip_edges()
			if line.begins_with("http"):
				var dep_name := line.rstrip("/").get_file().replace(".git", "")
				if not DirAccess.dir_exists_absolute(addons_dir + "/" + dep_name):
					log.call("🔗 Installing dependency: " + dep_name)
					clone_addon(root, line, log)

static func _build_class_map(addons_dir: String) -> Dictionary:
	var result := {}
	var dir := DirAccess.open(addons_dir)
	if not dir:
		return result
	dir.list_dir_begin()
	var name := dir.get_next()
	while name != "":
		if dir.current_is_dir() and not name.begins_with("."):
			var addon_path := addons_dir + "/" + name
			var url := git_remote(addon_path)
			if not url.is_empty():
				for gf: String in _find(addon_path, "*.gd"):
					for line: String in _read(gf).split("\n"):
						if line.begins_with("class_name "):
							var cname := line.replace("class_name ", "").strip_edges().split(" ")[0].split(":")[0]
							if not cname.is_empty():
								result[cname] = url
		name = dir.get_next()
	dir.list_dir_end()
	return result

static func _enable_plugin(root: String, cfg_rel: String, log: Callable) -> void:
	var pfile := root + "/project.godot"
	if not FileAccess.file_exists(pfile):
		return
	var res := "res://" + cfg_rel
	var content := _read(pfile)
	if res in content:
		return

	if "[editor_plugins]" in content:
		var re := RegEx.new()
		re.compile("enabled=PackedStringArray\\(([^)]*)\\)")
		var m := re.search(content)
		if m:
			var inner := m.get_string(1).strip_edges()
			var entry := '"' + res + '"'
			var new_inner := (inner + ", " + entry) if inner != "" else entry
			content = content.replace(m.get_string(), "enabled=PackedStringArray(" + new_inner + ")")
		else:
			content = content.replace("[editor_plugins]",
				'[editor_plugins]\n\nenabled=PackedStringArray("' + res + '")')
	else:
		content += '\n[editor_plugins]\n\nenabled=PackedStringArray("' + res + '")\n'

	_write(pfile, content)
	log.call("⚡ Enabled: " + cfg_rel)

# ─── REMOVE ADDON ────────────────────────────────────────────────────────────

static func remove_addon(root: String, addon_name: String, log: Callable) -> bool:
	var addons_dir := root + "/addons"
	var addon_path := addons_dir + "/" + addon_name

	if not DirAccess.dir_exists_absolute(addon_path):
		log.call("❌ Not found: " + addon_name)
		return false

	# Deps this addon uses
	var my_deps: Array[String] = []
	for line: String in _read(addon_path + "/DEPENDENCIES.txt").split("\n"):
		line = line.strip_edges()
		if line.begins_with("http"):
			my_deps.append(line.rstrip("/").get_file().replace(".git", ""))

	# Deps still needed by other addons
	var needed: Array[String] = []
	var dir := DirAccess.open(addons_dir)
	if dir:
		dir.list_dir_begin()
		var name := dir.get_next()
		while name != "":
			if dir.current_is_dir() and not name.begins_with(".") and name != addon_name:
				for line: String in _read(addons_dir + "/" + name + "/DEPENDENCIES.txt").split("\n"):
					line = line.strip_edges()
					if line.begins_with("http"):
						needed.append(line.rstrip("/").get_file().replace(".git", ""))
			name = dir.get_next()
		dir.list_dir_end()

	log.call("🗑️  Removing: " + addon_name)
	_rm_rf(addon_path)

	for dep: String in my_deps:
		if dep in needed:
			log.call("⏭️  Keeping: " + dep + " (used by others)")
		elif DirAccess.dir_exists_absolute(addons_dir + "/" + dep):
			log.call("🗑️  Removing orphaned dep: " + dep)
			_rm_rf(addons_dir + "/" + dep)

	log.call("✅ Cleanup complete.")
	return true

# ─── PUSH ALL ADDONS ─────────────────────────────────────────────────────────

static func push_all(root: String, log: Callable) -> bool:
	var addons_dir := root + "/addons"
	if not DirAccess.dir_exists_absolute(addons_dir):
		log.call("❌ No addons/ directory.")
		return false

	log.call("🔍 Pre-scanning classes...")
	var class_to_repo := {}
	var class_to_addon := {}
	_prescan_classes(addons_dir, class_to_repo, class_to_addon)

	log.call("🔍 Pre-scanning reverse deps...")
	var dependents_of := {}
	_prescan_reverse_deps(addons_dir, dependents_of)

	var updated := 0
	var dir := DirAccess.open(addons_dir)
	if not dir:
		return false

	dir.list_dir_begin()
	var name := dir.get_next()
	while name != "":
		if dir.current_is_dir() and not name.begins_with("."):
			var apath := addons_dir + "/" + name
			if DirAccess.dir_exists_absolute(apath + "/.git") and \
					FileAccess.file_exists(apath + "/plugin.cfg"):
				log.call("──────────────────────────")
				log.call("📦 Processing: " + name)
				if _process_one(root, name, class_to_repo, class_to_addon, dependents_of, log):
					updated += 1
		name = dir.get_next()
	dir.list_dir_end()

	log.call("──────────────────────────")
	log.call("🌳 Updating registry tree...")
	_update_tree(root, log)

	log.call("✅ Finished! %d updated." % updated)
	return true

static func _prescan_classes(addons_dir: String, class_to_repo: Dictionary, class_to_addon: Dictionary) -> void:
	var dir := DirAccess.open(addons_dir)
	if not dir:
		return
	dir.list_dir_begin()
	var name := dir.get_next()
	while name != "":
		if dir.current_is_dir() and not name.begins_with("."):
			var apath := addons_dir + "/" + name
			var url := git_remote(apath)
			if not url.is_empty():
				for gf: String in _find(apath, "*.gd"):
					for line: String in _read(gf).split("\n"):
						if line.begins_with("class_name "):
							var cname := line.replace("class_name ", "").strip_edges().split(" ")[0].split(":")[0]
							if not cname.is_empty():
								class_to_repo[cname] = url
								class_to_addon[cname] = name
		name = dir.get_next()
	dir.list_dir_end()

static func _prescan_reverse_deps(addons_dir: String, dependents_of: Dictionary) -> void:
	var dir := DirAccess.open(addons_dir)
	if not dir:
		return
	dir.list_dir_begin()
	var name := dir.get_next()
	while name != "":
		if dir.current_is_dir() and not name.begins_with("."):
			var apath := addons_dir + "/" + name
			var cfg := apath + "/plugin.cfg"
			var dep_file := apath + "/DEPENDENCIES.txt"
			if FileAccess.file_exists(cfg) and FileAccess.file_exists(dep_file):
				var info := parse_cfg(cfg)
				var depender_name: String = info.get("name", name)
				var depender_url := git_remote(apath)
				for line: String in _read(dep_file).split("\n"):
					line = line.strip_edges()
					if line.begins_with("http"):
						var clean := line.replace(".git", "")
						if clean not in dependents_of:
							dependents_of[clean] = []
						dependents_of[clean].append({"name": depender_name, "url": depender_url})
		name = dir.get_next()
	dir.list_dir_end()

static func _process_one(root: String, folder: String, c2r: Dictionary, c2a: Dictionary, deps_of: Dictionary, log: Callable) -> bool:
	var addons_dir := root + "/addons"
	var apath := addons_dir + "/" + folder
	var info := parse_cfg(apath + "/plugin.cfg")
	var a_name: String = info.get("name", folder)
	var a_desc: String = info.get("description", "")
	var a_author: String = info.get("author", "")
	var year := str(Time.get_datetime_dict_from_system()["year"])
	var cur_url := git_remote(apath)

	# Recursive dep scan
	var auto_deps: Array[String] = []
	var processed := [folder]
	var queue := [folder]
	while not queue.is_empty():
		var cur: String = queue.pop_front()
		var words: Dictionary = {}
		var re := RegEx.new()
		re.compile("\\b[A-Z][A-Za-z0-9_]+\\b")
		for gf: String in _find(addons_dir + "/" + cur, "*.gd"):
			for m: RegExMatch in re.search_all(_read(gf)):
				words[m.get_string()] = true
		for word: String in words:
			var target_a: String = c2a.get(word, "")
			if not target_a.is_empty() and target_a != folder:
				var url: String = c2r.get(word, "")
				if not url.is_empty() and url not in auto_deps:
					auto_deps.append(url)
					if target_a not in processed:
						queue.append(target_a)
						processed.append(target_a)

	# Manual deps
	var manual_deps: Array[String] = []
	var in_manual := false
	for line: String in _read(apath + "/DEPENDENCIES.txt").split("\n"):
		if MANUAL_MARKER in line:
			in_manual = true
			continue
		if in_manual and line.strip_edges().begins_with("http"):
			manual_deps.append(line.strip_edges())

	# Used-by
	var used_by: Array = deps_of.get(cur_url, [])

	# Generate README
	var clone_cmd := "clone-gd-addon " + cur_url + ".git"
	_write(apath + "/README.md", _readme(a_name, a_desc, a_author, year, clone_cmd, auto_deps, manual_deps, used_by))

	# Generate DOCUMENTATION
	var new_doc := _generate_doc(apath, a_name, a_desc, folder, c2r, c2a, auto_deps)
	var doc_path := apath + "/DOCUMENTATION.md"
	var old_doc := _read(doc_path)
	# Compare without the date line
	var nd := new_doc.split("\n")
	var od := old_doc.split("\n")
	if nd.size() > 1: nd.remove_at(1)
	if od.size() > 1: od.remove_at(1)
	if "\n".join(PackedStringArray(nd)) != "\n".join(PackedStringArray(od)):
		_write(doc_path, new_doc)

	# Registry sync
	if not cur_url.is_empty():
		_sync_registry(a_name, a_desc, cur_url, log)

	# Git commit & push
	var status_out := []
	OS.execute("git", PackedStringArray(["-C", apath, "status", "-s"]), status_out, true)
	if not status_out.is_empty() and not status_out[0].strip_edges().is_empty():
		_git(["add", "."], apath, log)
		_git(["commit", "-m", "docs: auto-sync v1.0.0"], apath, log)
		_git(["push", "origin", "main"], apath, log)
		return true
	log.call("✨ Nothing to update.")
	return false

# ─── README generation ───────────────────────────────────────────────────────

static func _readme(name: String, desc: String, author: String, year: String,
		clone_cmd: String, auto_deps: Array[String] = [], manual_deps: Array[String] = [],
		used_by: Array = []) -> String:
	var t := "# " + name + "\n\n" + desc + "\n\n"
	t += "## Installation\n\n"
	t += "Make sure to download the ChillCube Developer tools: https://github.com/ChillCube/ChillCube-Developer-Tools.git\n\n"
	t += "### Using the Godot Plugin\n"
	t += "Enable the **ChillCube Tools** plugin, then paste the repo URL into the Clone tab.\n\n"
	t += "### Linux / CLI\n"
	t += "```bash\n"
	t += (clone_cmd if not clone_cmd.is_empty() else "clone-gd-addon https://github.com/ChillCube/" + name + ".git") + "\n"
	t += "```\n\n"
	t += "## Documentation\nhttps://github.com/ChillCube/" + name + "/blob/main/DOCUMENTATION.md\n\n"
	t += "## Deinstallation\n"
	t += "Use the CC Tools panel in Godot, or run:\n"
	t += "```bash\nremove-gd-addon " + name + "\n```\n\n"
	t += "## For Developers\n```bash\npush-all-addons\n```\n"

	var all_deps := auto_deps.duplicate()
	for d: String in manual_deps:
		if d not in all_deps:
			all_deps.append(d)
	if not all_deps.is_empty():
		t += "\n## Dependencies\n\n"
		for url: String in all_deps:
			var dep_name := url.get_file().replace("Godot_", "")
			t += "- [%s](%s)\n" % [dep_name, url]

	if not used_by.is_empty():
		t += "\n## Used By\n%d other ChillCube addon(s) depend on this:\n\n" % used_by.size()
		for d: Dictionary in used_by:
			t += "- [%s](%s)\n" % [d.get("name", ""), d.get("url", "")]

	return t

# ─── DOCUMENTATION generation ────────────────────────────────────────────────

static func _generate_doc(apath: String, a_name: String, a_desc: String, folder: String,
		c2r: Dictionary, c2a: Dictionary, auto_deps: Array[String]) -> String:
	var doc := "# %s API Reference\n" % a_name
	doc += "Generated: %s\n\n%s\n" % [Time.get_date_string_from_system(), a_desc]

	if not auto_deps.is_empty():
		doc += "\n### 📦 Dependencies\n\n"
		doc += "| Source | Documentation | Repository |\n| :--- | :--- | :--- |\n"
		for url: String in auto_deps:
			var ref_name := url.get_file().replace("Godot_", "")
			doc += "| Code | [`%s`](%s/blob/main/DOCUMENTATION.md) | [Repo](%s) |\n" % [ref_name, url, url]
		doc += "\n---\n\n"

	for script: String in _find(apath, "*.gd"):
		var lines := _read(script).split("\n")
		var cname := ""
		var extends_val := ""
		for line: String in lines:
			if line.begins_with("class_name "):
				cname = line.replace("class_name ", "").strip_edges().split(" ")[0].split(":")[0]
			elif line.begins_with("extends "):
				extends_val = line.replace("extends ", "").strip_edges()
		if cname.is_empty():
			cname = script.get_file().get_basename()

		doc += "## Class: %s\n" % cname
		if not extends_val.is_empty():
			var link := ""
			if extends_val in c2r:
				if c2a.get(extends_val, "") == folder:
					link = "[%s](#class-%s)" % [extends_val, extends_val.to_lower()]
				else:
					link = "[%s](%s/blob/main/DOCUMENTATION.md)" % [extends_val, c2r[extends_val]]
			else:
				link = "[%s](https://docs.godotengine.org/en/stable/classes/class_%s.html)" % [extends_val, extends_val.to_lower()]
			doc += "**Inherits:** %s\n\n" % link
		else:
			doc += "\n"

		var exported := _parse_vars(lines, true)
		if not exported.is_empty():
			doc += "### ⚙️ Inspector Variables (Exported)\n| Property | Type | Default | Description |\n| :--- | :--- | :--- | :--- |\n"
			for v: Array in exported:
				doc += "| **%s** | `%s` | `%s` | %s |\n" % [v[0], v[1], v[2], v[3]]
			doc += "\n"

		var standard := _parse_vars(lines, false)
		if not standard.is_empty():
			doc += "### 💾 Class Variables (Standard)\n| Property | Type | Default | Description |\n| :--- | :--- | :--- | :--- |\n"
			for v: Array in standard:
				doc += "| **%s** | `%s` | `%s` | %s |\n" % [v[0], v[1], v[2], v[3]]
			doc += "\n"

		var sigs := _parse_signals(lines)
		if not sigs.is_empty():
			doc += "### 🔔 Signals\n| Signal | Arguments | Description |\n| :--- | :--- | :--- |\n"
			for s: Array in sigs:
				doc += "| **%s** | %s | %s |\n" % [s[0], s[1], s[2]]
			doc += "\n"

		var methods := _parse_methods(lines)
		if not methods.is_empty():
			doc += "### 🛠️ Methods\n| Method | Arguments | Returns | Description |\n| :--- | :--- | :--- | :--- |\n"
			for m: Array in methods:
				doc += "| **%s()** | %s | `%s` | %s |\n" % [m[0], m[1], m[2], m[3]]
			doc += "\n"

		doc += "---\n\n"
	return doc

static func _parse_vars(lines: PackedStringArray, exported: bool) -> Array:
	var result := []
	for line: String in lines:
		if "var" not in line or "##" not in line:
			continue
		if exported and "@export" not in line:
			continue
		if not exported and "@export" in line:
			continue
		var parts := line.split("##", true, 1)
		if parts.size() < 2:
			continue
		var desc := parts[1].strip_edges()
		var code := parts[0].strip_edges()
		var re := RegEx.new()
		re.compile("var\\s+(\\w+)")
		var vm := re.search(code)
		if not vm:
			continue
		var vname := vm.get_string(1)
		var vtype := "Variant"
		var type_re := RegEx.new()
		type_re.compile(":\\s*([A-Za-z_]\\w*)")
		var tm := type_re.search(code)
		if tm:
			vtype = tm.get_string(1)
		var vdefault := "-"
		if "=" in code:
			var def_re := RegEx.new()
			def_re.compile("=\\s*(.+?)(?:\\s*$)")
			var dm := def_re.search(parts[0])
			if dm:
				vdefault = dm.get_string(1).strip_edges()
		result.append([vname, vtype, vdefault, desc])
	return result

static func _parse_signals(lines: PackedStringArray) -> Array:
	var result := []
	for line: String in lines:
		if "signal " not in line or "##" not in line:
			continue
		var parts := line.split("##", true, 1)
		if parts.size() < 2:
			continue
		var desc := parts[1].strip_edges()
		var code := parts[0].strip_edges().replace("signal ", "").strip_edges()
		var sig_name := code
		var args := "-"
		if "(" in code:
			sig_name = code.split("(")[0]
			var raw := code.split("(")[1].replace(")", "").strip_edges()
			if not raw.is_empty():
				args = "`" + raw.replace(", ", "`<br>`") + "`"
		result.append([sig_name, args, desc])
	return result

static func _parse_methods(lines: PackedStringArray) -> Array:
	var result := []
	for line: String in lines:
		if "func " not in line or "##" not in line:
			continue
		var parts := line.split("##", true, 1)
		if parts.size() < 2:
			continue
		var desc := parts[1].strip_edges()
		var code := parts[0].strip_edges()
		var re := RegEx.new()
		re.compile("func\\s+(\\w+)\\(([^)]*)\\)")
		var fm := re.search(code)
		if not fm:
			continue
		var fname := fm.get_string(1)
		if fname.begins_with("_"):
			continue
		var raw_args := fm.get_string(2).strip_edges()
		var args := "`" + raw_args.replace(", ", "`<br>`") + "`" if not raw_args.is_empty() else "-"
		var ret := "void"
		if "->" in code:
			var rre := RegEx.new()
			rre.compile("->\\s*(\\w+)")
			var rm := rre.search(code)
			if rm:
				ret = rm.get_string(1)
		result.append([fname, args, ret, desc])
	return result

# ─── Registry ────────────────────────────────────────────────────────────────

static func _sync_registry(addon_name: String, addon_desc: String, addon_url: String, log: Callable) -> void:
	var tmp := OS.get_temp_dir() + "/.cc_reg_" + str(int(Time.get_unix_time_from_system()))
	if _exec("git", ["clone", "--depth", "1", ORG_REPO, tmp], Callable()) != OK:
		log.call("⚠️  Registry clone failed (skipping).")
		return

	var rfile := tmp + "/ADDONS.md"
	var content := _read(rfile)
	if content.is_empty():
		content = "# 🧊 ChillCube Addon Registry\n\n## Uncategorized\n"

	if addon_url not in content:
		var entry := "* [%s](%s) - %s" % [addon_name, addon_url, addon_desc]
		if "## Uncategorized" in content:
			content = content.replace("## Uncategorized\n", "## Uncategorized\n" + entry + "\n")
		else:
			content += "\n## Uncategorized\n" + entry + "\n"
		_write(rfile, content)
		_exec("git", ["-C", tmp, "add", "ADDONS.md"], Callable())
		_exec("git", ["-C", tmp, "commit", "-m", "registry: add " + addon_name], Callable())
		_exec("git", ["-C", tmp, "push", "origin", "main"], Callable())
		log.call("📋 Registry updated: " + addon_name)
	_rm_rf(tmp)

static func _update_tree(root: String, log: Callable) -> void:
	var tmp := OS.get_temp_dir() + "/.cc_tree_" + str(int(Time.get_unix_time_from_system()))
	if _exec("git", ["clone", "--depth", "1", ORG_REPO, tmp], Callable()) != OK:
		log.call("⚠️  Registry clone failed, skipping tree update.")
		return

	var addons_dir := root + "/addons"
	var rfile := tmp + "/ADDONS.md"
	var content := _read(rfile)

	# Strip old tree block
	var s_mark := "<!-- DEPENDENCY-TREE-START -->"
	var e_mark := "<!-- DEPENDENCY-TREE-END -->"
	if s_mark in content:
		var si := content.find(s_mark)
		var ei := content.find(e_mark)
		if ei != -1:
			content = content.substr(0, si) + content.substr(ei + e_mark.length())

	# Collect nodes
	var nodes := {}  # id -> {label, url, indegree, size, internal}
	var dir := DirAccess.open(addons_dir)
	if dir:
		dir.list_dir_begin()
		var name := dir.get_next()
		while name != "":
			if dir.current_is_dir() and not name.begins_with("."):
				var cfg := addons_dir + "/" + name + "/plugin.cfg"
				if FileAccess.file_exists(cfg):
					var info := parse_cfg(cfg)
					var raw: String = info.get("name", name)
					var id := _make_id(raw)
					var url := git_remote(addons_dir + "/" + name)
					nodes[id] = {"label": _clean_label(raw), "url": url,
						"indegree": 0, "size": _find(addons_dir + "/" + name, "*.gd").size(), "internal": true}
			name = dir.get_next()
		dir.list_dir_end()

	# Collect edges
	var edges: Array[Array] = []
	var deps_map := {}  # from_id -> [to_ids]
	var has_edge := {}
	var dir2 := DirAccess.open(addons_dir)
	if dir2:
		dir2.list_dir_begin()
		var name2 := dir2.get_next()
		while name2 != "":
			if dir2.current_is_dir() and not name2.begins_with("."):
				var cfg := addons_dir + "/" + name2 + "/plugin.cfg"
				var dep_file := addons_dir + "/" + name2 + "/DEPENDENCIES.txt"
				if FileAccess.file_exists(cfg) and FileAccess.file_exists(dep_file):
					var info := parse_cfg(cfg)
					var from_id := _make_id(info.get("name", name2))
					for line: String in _read(dep_file).split("\n"):
						line = line.strip_edges()
						if line.begins_with("http"):
							var dep_repo := line.rstrip("/").get_file().replace(".git", "")
							var to_id := _make_id(dep_repo)
							if from_id.is_empty() or to_id.is_empty():
								continue
							if to_id not in nodes:
								nodes[to_id] = {"label": _clean_label(dep_repo), "url": line.replace(".git", ""),
									"indegree": 0, "size": 0, "internal": false}
							nodes[to_id]["indegree"] = int(nodes[to_id]["indegree"]) + 1
							has_edge[from_id] = true
							has_edge[to_id] = true
							edges.append([from_id, to_id])
							if from_id not in deps_map:
								deps_map[from_id] = []
							deps_map[from_id].append(to_id)
			name2 = dir2.get_next()
		dir2.list_dir_end()

	# Topological layers
	var layers := {}
	for id: String in has_edge:
		if id not in deps_map or (deps_map[id] as Array).is_empty():
			layers[id] = 0
	var changed := true
	while changed:
		changed = false
		for id: String in has_edge:
			if id in layers:
				continue
			var all_ok := true
			var max_l := -1
			for dep: String in deps_map.get(id, []):
				if dep not in layers:
					all_ok = false
					break
				if int(layers[dep]) > max_l:
					max_l = int(layers[dep])
			if all_ok:
				layers[id] = max_l + 1
				changed = true
	for id: String in has_edge:
		if id not in layers:
			layers[id] = 0

	# Score
	var score := 0
	for id: String in nodes:
		var n: Dictionary = nodes[id]
		score += int(n.get("size", 0)) * 10 + int(n.get("indegree", 0)) * 50 + int(layers.get(id, 0)) * 20

	# Max layer
	var max_layer := 0
	for id: String in has_edge:
		if int(layers.get(id, 0)) > max_layer:
			max_layer = int(layers.get(id, 0))

	# Build Mermaid
	var m := "\n" + s_mark + "\n## 🌳 Dependency Tree\n\n"
	m += "```mermaid\n"
	m += "%%{init: {\"flowchart\": {\"curve\": \"linear\"}}}%%\n"
	m += "flowchart BT\n"
	m += "    classDef core  fill:#4a9eff,stroke:#2471d4,color:#fff\n"
	m += "    classDef shared fill:#a29bfe,stroke:#6c5ce7,color:#fff\n"
	m += "    classDef external fill:#fd9644,stroke:#e67e22,color:#fff\n\n"

	for l in range(max_layer + 1):
		var ids: Array[String] = []
		for id: String in has_edge:
			if int(layers.get(id, 0)) == l:
				ids.append(id)
		ids.sort()
		if ids.is_empty():
			continue
		m += '    subgraph Layer_%d["%s"]\n' % [l, "🧱 Layer 0 — Foundation" if l == 0 else "Layer %d" % l]
		for id: String in ids:
			m += '        %s["%s"]\n' % [id, (nodes.get(id, {}) as Dictionary).get("label", id)]
		m += "    end\n"
	m += "\n"

	for edge: Array in edges:
		var f: String = edge[0]
		var t: String = edge[1]
		if not f.is_empty() and not t.is_empty():
			m += "    %s --> %s\n" % [t, f]
	m += "\n"

	var edge_ids := has_edge.keys()
	edge_ids.sort()
	for id: String in edge_ids:
		var n: Dictionary = nodes.get(id, {})
		if not bool(n.get("internal", false)):
			m += "    class %s external\n" % id
		else:
			var deg := int(n.get("indegree", 0))
			if deg >= 2:
				m += "    class %s core\n" % id
			elif deg == 1:
				m += "    class %s shared\n" % id
	m += "\n"

	for id: String in edge_ids:
		var url: String = (nodes.get(id, {}) as Dictionary).get("url", "")
		if not url.is_empty():
			m += '    click %s href "%s" _blank\n' % [id, url]
	m += "```\n"

	# Standalone
	var standalone: Array[String] = []
	for id: String in nodes:
		if id not in has_edge:
			var n: Dictionary = nodes[id]
			var label: String = n.get("label", id)
			var url: String = n.get("url", "")
			standalone.append("[%s](%s)" % [label, url] if not url.is_empty() else label)
	if not standalone.is_empty():
		m += "\n**Standalone addons:** " + " · ".join(PackedStringArray(standalone)) + "\n"

	m += "\n**🏆 Progress Score: %d pts** — _+10 per .gd file · +50 per module that depends on you · +20 per dependency layer_\n" % score
	m += e_mark

	_write(rfile, content.rstrip("\n") + m)
	_exec("git", ["-C", tmp, "add", "ADDONS.md"], Callable())
	_exec("git", ["-C", tmp, "commit", "-m", "registry: update dependency tree"], Callable())
	_exec("git", ["-C", tmp, "push", "origin", "main"], Callable())
	_rm_rf(tmp)

static func _make_id(s: String) -> String:
	return s.to_lower().replace(" ", "_").replace("-", "_")

static func _clean_label(s: String) -> String:
	return s.replace("Godot_", "").replace("_", " ")
